apiVersion: v1
kind: Service
metadata:
  name: mongodb-shard2-headless-service
  namespace: daemonsl
  labels:
    name: mongodb-shard2
spec:
  ports:
  - port: 10007
    targetPort: 10007
  clusterIP: None
  selector:
    role: mongodb-shard2
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongodb-shard2
  namespace: daemonsl
spec:
  selector:
    matchLabels:
      role: mongodb-shard2 # has to match .spec.template.metadata.labels
  serviceName: mongodb-shard2-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shard2
        tier: maindb
        replicaset: ssShard2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - ssShard2
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-shard2-container
          image: mongo:2.6
          command:
            - "mongod"
            - "--port"
            - "10007"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "ssShard2"
            - "--dbpath"
            - "/mongo-disk"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 10007
          volumeMounts:
            - name: mongo-shard2-persistent-storage-claim
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongo-shard2-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
