apiVersion: v1
kind: Service
metadata:
  name: mongos-headless-service
  namespace: daemonsl
  labels:
    name: mongos
spec:
  ports:
  - port: 10007
    targetPort: 10007
  clusterIP: None
  selector:
    role: mongos
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongos
  namespace: daemonsl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        role: mongos
        tier: routers
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - routers
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongos-container
          image: mongo:2.6
          command:
            - "mongos"
            - "--port"
            - "10007"
            - "--bind_ip"
            - "0.0.0.0"
            - "--configdb"
            - "mongodb-configdb-0.mongodb-configdb-headless-service.daemonsl.svc.cluster.local:10009"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 10007
